/* Design preview only. Policy samples are generated by the existing V3 engine.
 * This page does not run a GSI receiver or create an OS overlay window.
 */
(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const names = {ak47:'AK-47',m4a4:'M4A4',m4a1s:'M4A1-S',fiveseven:'FN57',deagle:'沙鹰',kevlar:'半甲',kevlar_helmet:'甲 + 头',smoke:'烟',flash:'闪',he:'雷',molotov:'火',incendiary:'火',mp9:'MP9',mac10:'MAC-10',awp:'AWP',defusekit:'钳子'};
  const modes = {LIGHT:'半起',FULL:'全起',FORCE:'强起',PRESERVE:'ECO',AWP_PATH:'起 AWP'};
  const money = amount => '$' + Number(amount).toLocaleString('en-US');
  const scenes = window.ROUNDSENSE_SCENES;
  let scene = scenes[0];
  let chosen = null;
  let density = 'micro';
  let settings = {scale:100, opacity:84, position:'below-radar'};
  try { const stored=JSON.parse(localStorage.getItem('roundsense-hud-preview') || 'null'); if(stored && [80,85,90,95,100,105,110,115,120].includes(stored.scale) && Number.isInteger(stored.opacity) && stored.opacity>=45 && stored.opacity<=95 && ['below-radar','lower-left','lower-right'].includes(stored.position)) settings=stored; } catch { /* Browser-local storage is optional. */ }
  function text(id,value){$(id).textContent=value;}
  function getSelected(){return scene.policy.options.find(o=>o.id===chosen)||null;}
  function choices(){
    $('option-select').replaceChildren();
    for(const option of scene.policy.options){const node=document.createElement('option');node.value=option.id;node.textContent=modes[option.mode]+' · '+money(option.bundleSpend);$('option-select').append(node);}
    if(!scene.policy.options.length){const node=document.createElement('option');node.textContent='暂无方案';$('option-select').append(node);}
    chosen=scene.id==='light'?scene.policy.options.find(o=>o.mode==='LIGHT')?.id:scene.policy.defaultOptionId||scene.policy.options[0]?.id;
    $('option-select').value=chosen||'';
    $('option-select').disabled=!scene.policy.options.length||scene.phase!=='freezetime';
  }
  function updateDimensions(){requestAnimationFrame(()=>text('hud-dimensions',`${Math.round($('roundsense-hud').offsetWidth * settings.scale/100)} × ${Math.round($('roundsense-hud').offsetHeight * settings.scale/100)} px · ${density==='micro'?'微型':density==='minimal'?'极简':'标准'}`));}
  function applySettings(){
    document.documentElement.style.setProperty('--hud-scale',settings.scale/100);
    document.documentElement.style.setProperty('--hud-alpha',settings.opacity/100);
    $('hud-anchor').className='hud-anchor '+settings.position;
    $('scale-range').value=settings.scale;$('opacity-range').value=settings.opacity;$('position-select').value=settings.position;
    text('scale-output',settings.scale+'%');text('opacity-output',settings.opacity+'%');
    try{localStorage.setItem('roundsense-hud-preview',JSON.stringify(settings));}catch{ /* Optional persistence. */ }
    updateDimensions();
  }
  function render(){
    const option=getSelected();
    const visible=scene.phase==='freezetime';
    $('hud-anchor').hidden=!visible;$('hidden-state').hidden=visible;
    const stale=scene.phase==='stale';
    text('native-phase',stale?'状态未知':scene.phase==='live'?'回合进行':'冻结时间');
    text('native-cash','$'+scene.money);
    text('stage-status-text',visible?'冻结时间 · HUD 可见':stale?'数据过期 · HUD 隐藏':'回合进行 · HUD 隐藏');
    text('hidden-description',stale?'旧购买建议不继续留在画面上。':'回合进行中，视野留给游戏。');
    text('hud-round',scene.side+' · R'+scene.round);
    text('hud-cash',money(scene.money));
    $('game-stage').classList.toggle('unavailable',!option);
    if(!option){
      const pistol=scene.policy.status==='UNSUPPORTED_POLICY_EVIDENCE';
      text('hud-choice','暂无建议');text('hud-mode',pistol?'手枪局':'信息不足');
      $('hud-budget').replaceChildren();text('hud-purchases',pistol?'当前未支持手枪局购买建议':'等待败方奖励信息');
      text('hud-spend','—');text('hud-next','—');text('hud-capability','暂不预测');text('hud-assumption','缺失信息不补造数值');
      updateDimensions();return;
    }
    text('hud-choice',option.adviceStrength==='DOMINANT'?'优先方案':'可选方案');
    text('hud-mode',modes[option.mode]);
    const boundary=scene.policy.futureAffordability.boundaries.find(b=>b.capability===option.spendingGuidance.protectedCapability);
    const budgetLabel=boundary?'投入 ≤ ':option.mode==='PRESERVE'?'尽量保留 ': '此方案 ';
    $('hud-budget').replaceChildren(document.createTextNode(budgetLabel));
    const budget=document.createElement('b');budget.textContent=money(boundary?boundary.maxSpendNow:option.mode==='PRESERVE'?scene.money:option.bundleSpend);$('hud-budget').append(budget);
    const purchaseText=option.purchases.map(p=>(names[p.item]||p.item)+(p.quantity>1?' ×'+p.quantity:'')).join(' · ');
    const result=option.resultingInventory;
    const grouped=option.purchases.length>3?[(result.primary&&names[result.primary])||'主武器',result.hasHelmet?'甲头':result.armor>0?'半甲':'',result.grenades.length?result.grenades.length+' 道具':''].filter(Boolean).join(' · '):purchaseText;
    text('hud-purchases',option.purchases.length?grouped:'无需购买');
    $('hud-purchases').title=purchaseText||'无需购买';
    text('hud-spend',money(option.bundleSpend));
    const next=option.trajectory.find(s=>s.id==='LOSS_NO_PLANT')?.nextMoney;
    text('hud-next',next?'≈ '+money(next.min):'未知');
    const available=next?scene.policy.futureAffordability.boundaries.filter(b=>b.reachableWithNoSpend&&next.min>=b.targetCash):[];
    const utility=available.some(b=>b.capability==='RIFLE_ARMOR_BASIC_UTILITY');
    text('hud-capability',utility?(density==='micro'?'长枪甲道具':'长枪 + 甲 + 基础道具'):available.length?(density==='micro'?'长枪甲':'长枪 + 甲'):scene.policy.futureAffordability.status==='PROJECTED'?(density==='micro'?'长枪钱不足':'长枪购置现金不足'):(density==='micro'?'未评估':'购买能力未评估'));
    $('roundsense-hud').title='所选可选方案；败后按无额外收入、T 未下包、下一局重新购买计算。';
    text('hud-assumption',scene.side==='T'?'未下包、无额外收入 · 按重新购买计算':'无额外收入 · 按重新购买计算');
    updateDimensions();
  }
  $('scene-select').addEventListener('change',e=>{scene=scenes.find(s=>s.id===e.target.value)||scenes[0];choices();render();});
  $('option-select').addEventListener('change',e=>{chosen=e.target.value;render();});
  document.querySelectorAll('[data-density]').forEach(button=>button.addEventListener('click',()=>{density=button.dataset.density;document.body.classList.toggle('minimal',density==='minimal');document.body.classList.toggle('micro',density==='micro');document.querySelectorAll('[data-density]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});render();}));
  $('settings-button').addEventListener('click',()=>{const hidden=!$('appearance-controls').hidden;$('appearance-controls').hidden=hidden;$('settings-button').setAttribute('aria-expanded',String(!hidden));});
  $('scale-range').addEventListener('input',e=>{settings.scale=Number(e.target.value);applySettings();});
  $('opacity-range').addEventListener('input',e=>{settings.opacity=Number(e.target.value);applySettings();});
  $('position-select').addEventListener('change',e=>{settings.position=e.target.value;applySettings();});
  $('reset-button').addEventListener('click',()=>{settings={scale:100,opacity:84,position:'below-radar'};applySettings();});
  $('fullscreen-button').addEventListener('click',async()=>{try{await $('game-stage').requestFullscreen();}catch{text('fullscreen-button','当前环境不支持全屏');}});
  window.addEventListener('resize',updateDimensions);
  choices();applySettings();render();
})();
